---
- name: apache startup
  hosts: localhost
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: latest

    - name: checking service status
      command: systemctl status apache2.service
      register: result

    - name: print apache server status
      debug:
        var: result

